/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resumefilter;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;

/**
 *
 * @author Babar Hussain
 */
public class location extends javax.swing.JPanel {

    /**
     * Creates new form location
     */
    public location(String location) {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foundLocationField = new javax.swing.JTextField();
        editfoundLocationField = new javax.swing.JLabel();

        foundLocationField.setEditable(false);
        foundLocationField.setText("D:\\BAHL Projects\\Resume 2022");
        foundLocationField.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.GRAY));

        editfoundLocationField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/edit-53-32.png"))); // NOI18N
        editfoundLocationField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editfoundLocationFieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(foundLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editfoundLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editfoundLocationField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(foundLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editfoundLocationFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editfoundLocationFieldMouseClicked
        if (!foundLocationField.getText().isEmpty()) {
            JFileChooser chooser = new JFileChooser();
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            chooser.setCurrentDirectory(new java.io.File(foundLocationField.getText()));
            chooser.setDialogTitle("Select Location to save Filterd Resumes");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                foundLocationField.setText(chooser.getSelectedFile().getAbsolutePath());
            }
        }

    }//GEN-LAST:event_editfoundLocationFieldMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel editfoundLocationField;
    private javax.swing.JTextField foundLocationField;
    // End of variables declaration//GEN-END:variables
}
